/*
 * Facebook Marketing API
 *
 * This is a generated connector for [Facebook Marketing API v12.0](https://developers.facebook.com/docs/marketing-apis) OpenAPI specification.  Facebook is an American online social media and social networking service owned by Facebook, Inc.Facebook Marketing  APIs are a collection of Graph API endpoints that can be used to help you advertise on Facebook.
 *
 * The version of the OpenAPI document: v12.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TimeRange : Date range used to aggregate insights metrics
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeRange {
	/// A date in the format of \"YYYY-MM-DD\", which means from the beginning midnight of that day
	#[serde(rename = "since", skip_serializing_if = "Option::is_none")]
	pub since: Option<String>,
	/// A date in the format of \"YYYY-MM-DD\", which means to the beginning midnight of the following day
	#[serde(rename = "until", skip_serializing_if = "Option::is_none")]
	pub until: Option<String>,
}

impl TimeRange {
	/// Date range used to aggregate insights metrics
	pub fn new() -> TimeRange {
		TimeRange {
			since: None,
			until: None,
		}
	}

	pub fn to_string(&self) -> String {
		json::to_string(self).unwrap()
	}
}
