[jobs.default]
command = ["cargo", "run", "-p", "web-server"]
need_stdout = true
watch = ["crates/", "Cargo.toml", ".cargo/"]
ignore = ["target/"]
background = false
on_change_strategy = "kill_then_restart"

[jobs.clippy]
command = ["cargo", "clippy"]

[jobs.test]
command = ["cargo", "test"]

[keybindings]
c = "job:clippy"
t = "job:test"
