[workspace.lints.rust]
unsafe_code = "forbid"
# unused = "allow" # For experimental dev.

[workspace]
resolver = "2"
members = [
    # -- Application Libraries
    "crates/libs/lib-utils", # e.g., base64, time.
    "crates/libs/lib-rpc",   # e.g., app rpc handlers (using rpc-router crate)
    "crates/libs/lib-auth",  # e.g., for pwd, token.
    "crates/libs/lib-core",  # e.g., model, ctx, config.
    "crates/libs/serde-json-debugging",

    # -- Application Services
    "crates/services/web-server",
    "crates/services/token-service",

    # -- Tools
    "crates/tools/gen-key",

    # -- Sites
    "crates/sites/site_1", 
    "crates/libs/js_macro", 

    # -- SDKs
    "crates/libs/lib-directus",
    "crates/libs/lib-active-campaign", 
    "crates/libs/lib-anythingllm", 
    "crates/libs/lib-sdk",
]

# NOTE: Only the crates that are utilized in two or more sub-crates and benefit from global management
#       are handled in workspace.dependencies. Other strategies may also be valid.
[workspace.dependencies]
# -- Serde
serde_with = {version = "3", features = ["time_0_3"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_urlencoded = { version = "0.7" }
url_serde = { version = "0.2" }
url = { version = "2", features = ["serde"] }

tokio = { version = "1", features = ["full"] }
# -- Data
# Note: we lock modql version during rcs
modql = { version = "0.4", features = ["with-sea-query"]}
# -- JSON-RPC
# Lock to specific version during 0.1.x
rpc-router = { version = "=0.1.3" } 
# -- Others
# NOTE: time is set as `<0.3.35` to match sea-query-binder version 0.6.0-rc.2 (see https://github.com/SeaQL/sea-query/issues/772)
#       will set back to `0.3` as soon as sea-query-binder 0.6.0-rc is fix
time = {version = "0.3", features = ["formatting", "parsing", "serde"]}
derive_more = {version = "1.0.0", features = ["from", "display"] }

reqwest = { version = "0.12", features = ["json"] }

strum = { version = "0.26", features = ["derive"] }
strum_macros = { version = "0.26" }

[workspace.metadata.scripts]
w = "crs bundle & pkill web-server & cargo watch -q -c -w crates/services/web-server/src/ -w crates/libs/ -w .cargo/ -w crates/sites/ -w vite-alpine/ -x \"run -p web-server\" & concurrently \"npm --prefix vite-alpine run dev\""
bundle = "rm -rf web-folder/js && npm --prefix vite-alpine run build"
devdb = "docker run --rm --name pg -p 5432:5432 -e POSTGRES_PASSWORD=welcome postgres:16"
