[workspace.lints.rust]
unsafe_code = "forbid"

[workspace]
resolver = "2"
members = [
    # -- Application Libraries
    "crates/libs/lib-utils",
    "crates/libs/lib-auth",
    "crates/libs/lib-core",
    "crates/libs/serde-json-debugging",

    # -- Application Services
    "crates/services/web-server",
    "crates/services/token-service",

    # -- Tools
    "crates/tools/gen-key",

    # -- Sites
    "crates/sites/site_1", 
    "crates/libs/js_macro", 

    # -- SDKs
    "crates/libs/lib-directus",
    "crates/libs/lib-active-campaign", 
    "crates/libs/lib-anythingllm", 
    "crates/libs/lib-sdk", "crates/tools/split_structs",
]

[workspace.dependencies]

serde_with = {version = "3", features = ["time_0_3"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_urlencoded = { version = "0.7" }
url_serde = { version = "0.2" }
url = { version = "2", features = ["serde"] }

tokio = { version = "1", features = ["full"] }
time = {version = "0.3", features = ["formatting", "parsing", "serde"]}
derive_more = {version = "1.0.0", features = ["from", "display"] }

reqwest = { version = "0.12", features = ["json"] }

strum = { version = "0.26", features = ["derive"] }
strum_macros = { version = "0.26" }

sqlx = { version = "0.8", features = [ "macros", "postgres", "uuid" , "runtime-tokio-native-tls"] }

[workspace.metadata.scripts]
w = "cargo run-script bundle & cargo run-script watch"
bundle = "cargo run-script bundle-site-1"
watch = "pkill web-server & cargo watch -q -c -w crates/services/web-server/src/ -w crates/libs/ -w .cargo/ -w crates/sites/ -x \"run -p web-server\""
bundle-site-1 = "rm -rf crates/sites/site_1/src/web-folder/js && npm --prefix crates/sites/site_1/src/vite-alpine run build"
devdb = "docker run --rm --name pg -p 5432:5432 -e POSTGRES_PASSWORD=welcome postgres:16"
merge_directus='pg2rs --connection-string $(grep DIRECTUS_CONNECTION_STRING .cargo/config.toml | sed -E "s/.*DIRECTUS_CONNECTION_STRING=\"?([^\"]+)\"?.*/\1/") --custom-traits ormlite::Model --schema public --output_file crates/libs/lib-core/src/model/structs.rs'
