# rustfmt doc - https://rust-lang.github.io/rustfmt/
unstable_features = true

hard_tabs = false
tab_spaces = 2
edition = "2024"

# For recording
max_width = 85
# chain_width = 40
# array_width = 40

imports_granularity = "Crate"
reorder_imports = true
