/*
 * Dynamic API Specification
 *
 * This is a dynamically generated API specification for all endpoints existing on the current project.
 *
 * The version of the OpenAPI document: 11.2.2
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AcceptInviteRequest {
	/// Accept invite token.
	#[serde(rename = "token", skip_serializing_if = "Option::is_none")]
	pub token: Option<String>,
	/// Password of the user.
	#[serde(rename = "password", skip_serializing_if = "Option::is_none")]
	pub password: Option<String>,
}

impl AcceptInviteRequest {
	pub fn new() -> AcceptInviteRequest {
		AcceptInviteRequest {
			token: None,
			password: None,
		}
	}
}
