/*
 * Dynamic API Specification
 *
 * This is a dynamically generated API specification for all endpoints existing on the current project.
 *
 * The version of the OpenAPI document: 11.2.2
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FlowsOperationsInner {
	String(uuid::Uuid),
	Operations(Box<super::Operations>),
}

impl Default for FlowsOperationsInner {
	fn default() -> Self {
		Self::String(Default::default())
	}
}
