/*
 * Dynamic API Specification
 *
 * This is a dynamically generated API specification for all endpoints existing on the current project.
 *
 * The version of the OpenAPI document: 11.2.2
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemsEbooksTags {
	#[serde(rename = "id", skip_serializing_if = "Option::is_none")]
	pub id: Option<i32>,
	#[serde(
		rename = "ebooks_id",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub ebooks_id: Option<Option<Box<super::ItemsEbooksTranslationsEbooksId>>>,
	#[serde(
		rename = "tags_id",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub tags_id: Option<Option<Box<super::ItemsTagsTranslationsTagsId>>>,
}

impl ItemsEbooksTags {
	pub fn new() -> ItemsEbooksTags {
		ItemsEbooksTags {
			id: None,
			ebooks_id: None,
			tags_id: None,
		}
	}
}
