/*
 * Dynamic API Specification
 *
 * This is a dynamically generated API specification for all endpoints existing on the current project.
 *
 * The version of the OpenAPI document: 11.2.2
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// RevisionsActivity : Unique identifier for the activity record.
/// Unique identifier for the activity record.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RevisionsActivity {
	Integer(i32),
	Activity(Box<super::Activity>),
}

impl Default for RevisionsActivity {
	fn default() -> Self {
		Self::Integer(Default::default())
	}
}
/// Action that was performed.
#[derive(
	Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize,
)]
pub enum Action {
	#[serde(rename = "create")]
	Create,
	#[serde(rename = "update")]
	Update,
	#[serde(rename = "delete")]
	Delete,
	#[serde(rename = "login")]
	Login,
}

impl Default for Action {
	fn default() -> Action {
		Self::Create
	}
}
