/*
 * Dynamic API Specification
 *
 * This is a dynamically generated API specification for all endpoints existing on the current project.
 *
 * The version of the OpenAPI document: 11.2.2
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateCommentsRequestData {
	/// Which collection this collection comment is for.
	#[serde(rename = "collection")]
	pub collection: String,
	#[serde(rename = "item", skip_serializing_if = "Option::is_none")]
	pub item: Option<String>,
	#[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
	pub comment: Option<String>,
}

impl UpdateCommentsRequestData {
	pub fn new(collection: String) -> UpdateCommentsRequestData {
		UpdateCommentsRequestData {
			collection,
			item: None,
			comment: None,
		}
	}
}
