/*
 * Dynamic API Specification
 *
 * This is a dynamically generated API specification for all endpoints existing on the current project.
 *
 * The version of the OpenAPI document: 11.2.2
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateWebhooksRequest {
	#[serde(rename = "data", skip_serializing_if = "Option::is_none")]
	pub data: Option<Box<super::CreateWebhookRequest>>,
	#[serde(rename = "keys", skip_serializing_if = "Option::is_none")]
	pub keys: Option<Vec<String>>,
}

impl UpdateWebhooksRequest {
	pub fn new() -> UpdateWebhooksRequest {
		UpdateWebhooksRequest {
			data: None,
			keys: None,
		}
	}
}
