/*
 * Dynamic API Specification
 *
 * This is a dynamically generated API specification for all endpoints existing on the current project.
 *
 * The version of the OpenAPI document: 11.2.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWebhookRequest {
	/// The name of the webhook.
	#[serde(rename = "name", skip_serializing_if = "Option::is_none")]
	pub name: Option<String>,
	/// Method used in the webhook.
	#[serde(rename = "method", skip_serializing_if = "Option::is_none")]
	pub method: Option<String>,
	/// The url of the webhook.
	#[serde(rename = "url", skip_serializing_if = "Option::is_none")]
	pub url: Option<String>,
	/// The status of the webhook.
	#[serde(rename = "status", skip_serializing_if = "Option::is_none")]
	pub status: Option<String>,
	/// If yes, send the content of what was done
	#[serde(rename = "data", skip_serializing_if = "Option::is_none")]
	pub data: Option<bool>,
	/// The actions that triggers this webhook.
	#[serde(
		rename = "actions",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub actions: Option<Option<serde_json::Value>>,
	/// The collections that triggers this webhook.
	#[serde(
		rename = "system-collections",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub system_collections: Option<Option<serde_json::Value>>,
}

impl CreateWebhookRequest {
	pub fn new() -> CreateWebhookRequest {
		CreateWebhookRequest {
			name: None,
			method: None,
			url: None,
			status: None,
			data: None,
			actions: None,
			system_collections: None,
		}
	}
}
