/*
 * Dynamic API Specification
 *
 * This is a dynamically generated API specification for all endpoints existing on the current project.
 *
 * The version of the OpenAPI document: 11.2.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPermissions200Response {
	#[serde(rename = "data", skip_serializing_if = "Option::is_none")]
	pub data: Option<Vec<models::Permissions>>,
	#[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
	pub meta: Option<Box<models::XMetadata>>,
}

impl GetPermissions200Response {
	pub fn new() -> GetPermissions200Response {
		GetPermissions200Response {
			data: None,
			meta: None,
		}
	}
}
