/*
 * Dynamic API Specification
 *
 * This is a dynamically generated API specification for all endpoints existing on the current project.
 *
 * The version of the OpenAPI document: 11.2.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemsLanguages {
	#[serde(rename = "code", skip_serializing_if = "Option::is_none")]
	pub code: Option<String>,
	#[serde(
		rename = "direction",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub direction: Option<Option<String>>,
	#[serde(
		rename = "name",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub name: Option<Option<String>>,
}

impl ItemsLanguages {
	pub fn new() -> ItemsLanguages {
		ItemsLanguages {
			code: None,
			direction: None,
			name: None,
		}
	}
}
