/*
 * Dynamic API Specification
 *
 * This is a dynamically generated API specification for all endpoints existing on the current project.
 *
 * The version of the OpenAPI document: 11.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OperationsResolve : The operation triggered when the current operation succeeds (or `then` logic of a condition operation).
/// The operation triggered when the current operation succeeds (or `then` logic of a condition operation).
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OperationsResolve {
    String(String),
    Operations(Box<models::Operations>),
}

impl Default for OperationsResolve {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

