/*
 * Coolify
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeployByTagOrUuid200ResponseDeploymentsInner {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "resource_uuid", skip_serializing_if = "Option::is_none")]
    pub resource_uuid: Option<String>,
    #[serde(rename = "deployment_uuid", skip_serializing_if = "Option::is_none")]
    pub deployment_uuid: Option<String>,
}

impl DeployByTagOrUuid200ResponseDeploymentsInner {
    pub fn new() -> DeployByTagOrUuid200ResponseDeploymentsInner {
        DeployByTagOrUuid200ResponseDeploymentsInner {
            message: None,
            resource_uuid: None,
            deployment_uuid: None,
        }
    }
}

