/*
 * Coolify
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecuteCommandApplicationRequest {
    /// Command to execute.
    #[serde(rename = "command", skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
}

impl ExecuteCommandApplicationRequest {
    pub fn new() -> ExecuteCommandApplicationRequest {
        ExecuteCommandApplicationRequest {
            command: None,
        }
    }
}

