//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "directus_access")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	pub role: Option<Uuid>,
	pub user: Option<Uuid>,
	pub policy: Uuid,
	pub sort: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::directus_policies::Entity",
		from = "Column::Policy",
		to = "super::directus_policies::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	DirectusPolicies,
	#[sea_orm(
		belongs_to = "super::directus_roles::Entity",
		from = "Column::Role",
		to = "super::directus_roles::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	DirectusRoles,
	#[sea_orm(
		belongs_to = "super::directus_users::Entity",
		from = "Column::User",
		to = "super::directus_users::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	DirectusUsers,
}

impl Related<super::directus_policies::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::DirectusPolicies.def()
	}
}

impl Related<super::directus_roles::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::DirectusRoles.def()
	}
}

impl Related<super::directus_users::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::DirectusUsers.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
