//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod articles;
pub mod articles_translations;
pub mod directus_access;
pub mod directus_activity;
pub mod directus_collections;
pub mod directus_comments;
pub mod directus_dashboards;
pub mod directus_extensions;
pub mod directus_fields;
pub mod directus_files;
pub mod directus_flows;
pub mod directus_folders;
pub mod directus_migrations;
pub mod directus_notifications;
pub mod directus_operations;
pub mod directus_panels;
pub mod directus_permissions;
pub mod directus_policies;
pub mod directus_presets;
pub mod directus_relations;
pub mod directus_revisions;
pub mod directus_roles;
pub mod directus_sessions;
pub mod directus_settings;
pub mod directus_shares;
pub mod directus_translations;
pub mod directus_users;
pub mod directus_versions;
pub mod directus_webhooks;
pub mod ebooks;
pub mod ebooks_directus_users;
pub mod ebooks_translations;
pub mod languages;
pub mod spatial_ref_sys;
